# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CODER_V3_py.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1454, 1092)
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setGeometry(QtCore.QRect(20, 20, 261, 301))
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_1)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_2.setObjectName("s1__box_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_2)
        self.state_label = QtWidgets.QLabel(self.formGroupBox)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.state_label)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox)
        self.open_button.setObjectName("open_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.open_button)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox)
        self.close_button.setObjectName("close_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.close_button)
        self.open_btn_cam = QtWidgets.QPushButton(self.formGroupBox)
        self.open_btn_cam.setObjectName("open_btn_cam")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.open_btn_cam)
        self.close_btn_cam = QtWidgets.QPushButton(self.formGroupBox)
        self.close_btn_cam.setObjectName("close_btn_cam")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.close_btn_cam)
        self.verticalGroupBox = QtWidgets.QGroupBox(Form)
        self.verticalGroupBox.setGeometry(QtCore.QRect(920, 30, 451, 431))
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_show_QR = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_show_QR.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_show_QR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_show_QR.setObjectName("label_show_QR")
        self.verticalLayout.addWidget(self.label_show_QR)
        self.formGroupBox1 = QtWidgets.QGroupBox(Form)
        self.formGroupBox1.setGeometry(QtCore.QRect(20, 320, 261, 141))
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox1)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_cap = QtWidgets.QLabel(self.formGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cap.setFont(font)
        self.label_cap.setObjectName("label_cap")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_cap)
        self.label_sp = QtWidgets.QLabel(self.formGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sp.setFont(font)
        self.label_sp.setObjectName("label_sp")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_sp)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(920, 500, 441, 141))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.label.setObjectName("label")
        self.textMAC = QtWidgets.QTextEdit(self.groupBox)
        self.textMAC.setGeometry(QtCore.QRect(10, 30, 421, 31))
        self.textMAC.setObjectName("textMAC")
        self.textTH = QtWidgets.QTextEdit(self.groupBox)
        self.textTH.setGeometry(QtCore.QRect(120, 90, 31, 31))
        self.textTH.setObjectName("textTH")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(170, 90, 111, 31))
        self.label_2.setObjectName("label_2")
        self.textNum = QtWidgets.QTextEdit(self.groupBox)
        self.textNum.setGeometry(QtCore.QRect(280, 90, 31, 31))
        self.textNum.setObjectName("textNum")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(330, 90, 81, 31))
        self.label_3.setObjectName("label_3")
        self.RSSiResult = QtWidgets.QTextEdit(self.groupBox)
        self.RSSiResult.setGeometry(QtCore.QRect(400, 90, 31, 31))
        self.RSSiResult.setObjectName("RSSiResult")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 470, 881, 611))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_show_camera = QtWidgets.QLabel(self.groupBox_2)
        self.label_show_camera.setGeometry(QtCore.QRect(10, 30, 861, 571))
        self.label_show_camera.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_show_camera.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_show_camera.setScaledContents(False)
        self.label_show_camera.setWordWrap(False)
        self.label_show_camera.setObjectName("label_show_camera")
        self.s3__send_button = QtWidgets.QPushButton(Form)
        self.s3__send_button.setGeometry(QtCore.QRect(930, 740, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.s3__send_button.setFont(font)
        self.s3__send_button.setObjectName("s3__send_button")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(920, 860, 431, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.groupBox_3)
        self.s2__receive_text.setGeometry(QtCore.QRect(10, 60, 261, 101))
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.s2__clear_button = QtWidgets.QPushButton(self.groupBox_3)
        self.s2__clear_button.setGeometry(QtCore.QRect(290, 80, 131, 71))
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(300, 30, 601, 431))
        self.groupBox_4.setObjectName("groupBox_4")
        self.text_code128 = QtWidgets.QTextEdit(self.groupBox_4)
        self.text_code128.setGeometry(QtCore.QRect(310, 310, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_code128.setFont(font)
        self.text_code128.setObjectName("text_code128")
        self.label_show_result = QtWidgets.QLabel(self.groupBox_4)
        self.label_show_result.setGeometry(QtCore.QRect(10, 310, 281, 111))
        self.label_show_result.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_show_result.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_show_result.setObjectName("label_show_result")
        self.label_show_Code128 = QtWidgets.QLabel(self.groupBox_4)
        self.label_show_Code128.setGeometry(QtCore.QRect(20, 50, 571, 231))
        self.label_show_Code128.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_show_Code128.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_show_Code128.setObjectName("label_show_Code128")
        self.push_Code128 = QtWidgets.QPushButton(self.groupBox_4)
        self.push_Code128.setGeometry(QtCore.QRect(310, 380, 281, 41))
        self.push_Code128.setObjectName("push_Code128")
        self.detecBtn = QtWidgets.QPushButton(Form)
        self.detecBtn.setGeometry(QtCore.QRect(930, 660, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.detecBtn.setFont(font)
        self.detecBtn.setObjectName("detecBtn")
        self.verticalGroupBox.raise_()
        self.formGroupBox.raise_()
        self.formGroupBox.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.s3__send_button.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.detecBtn.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.formGroupBox.setTitle(_translate("Form", "设置"))
        self.s1__lb_1.setText(_translate("Form", "串口检测："))
        self.s1__box_1.setText(_translate("Form", "检测串口"))
        self.s1__lb_2.setText(_translate("Form", "串口选择："))
        self.open_button.setText(_translate("Form", "打开串口"))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.open_btn_cam.setText(_translate("Form", "打开摄像头"))
        self.close_btn_cam.setText(_translate("Form", "关闭摄像头"))
        self.verticalGroupBox.setTitle(_translate("Form", "二维码"))
        self.label_show_QR.setText(_translate("Form", "TextLabel"))
        self.formGroupBox1.setTitle(_translate("Form", "状态"))
        self.label_cap.setText(_translate("Form", "摄像头未连接"))
        self.label_sp.setText(_translate("Form", "串口未连接"))
        self.groupBox.setTitle(_translate("Form", "MAC"))
        self.label.setText(_translate("Form", "RSSi阈值："))
        self.textTH.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-45</p></body></html>"))
        self.label_2.setText(_translate("Form", "索引数量："))
        self.label_3.setText(_translate("Form", "RSSI："))
        self.groupBox_2.setTitle(_translate("Form", "摄像头"))
        self.label_show_camera.setText(_translate("Form", "TextLabel"))
        self.s3__send_button.setText(_translate("Form", "生成二维码"))
        self.groupBox_3.setTitle(_translate("Form", "串口调试"))
        self.s2__clear_button.setText(_translate("Form", "清除"))
        self.groupBox_4.setTitle(_translate("Form", "条形码"))
        self.label_show_result.setText(_translate("Form", "TextLabel"))
        self.label_show_Code128.setText(_translate("Form", "TextLabel"))
        self.push_Code128.setText(_translate("Form", "修改条形码"))
        self.detecBtn.setText(_translate("Form", "生成条形码"))

